name: Run Gradle on Tags and Master
on:
  push:
    branches:
      - main
      - 'releases/**'
jobs:
  gradle:
    strategy:
      matrix:
        java: [8,11,17]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build